version: 2.1

jobs:
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout  # Check out the code
      - run:
          name: Run SonarCloud Analysis
          command: |
            docker run \
              --rm \
              -e SONAR_HOST_URL="https://sonarcloud.io" \
              -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=keegan-scorgie_APDS7311POE" \
              -e SONAR_LOGIN=$SONAR_TOKEN \
              -v "$(pwd)":/usr/src \
              sonarsource/sonar-scanner-cli
workflows:
  version: 2
  sonarcloud-analysis:
    jobs:
      - sonarqube