version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Set up SonarCloud environment variables
          command: |
            export SONAR_HOST_URL="https://sonarcloud.io"
            export SONAR_LOGIN="0fb0e746eb902bbedb862786274bc3dbbfdd61af"
            export SONAR_PROJECT_KEY="keegan-scorgie_APDS7311POE"
            export SONAR_ORG="keegan-scorgie"
      - run:
          name: Run SonarCloud analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_LOGIN

workflows:
  version: 2
  build:
    jobs:
      - build