version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  sonarqube:
    executor: python-executor
    steps:
      - checkout  # Checks out the source code
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.tar.gz https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.tar.gz
            mv sonar-scanner-*/bin/* /usr/local/bin/
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=keegan-scorgie_APDS7311POE \
              -Dsonar.organization=keegan-scorgie \
              -Dsonar.login=$SONAR_TOKEN
workflows:
  version: 2
  build_and_test:
    jobs:
      - sonarqube