version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a Python 3.9 Docker image compatible with your dependencies
    environment:
      SONAR_TOKEN: $SONAR_TOKEN  # Set environment variable from CircleCI secrets
      SONAR_PROJECT_KEY: <your-sonarqube-project-key>  # Replace with your SonarQube project key
      SONAR_ORGANIZATION: <your-sonarqube-organization>  # Replace with your SonarQube organization
    steps:
      - checkout  # Checkout the code from the repo

      - run:
          name: Install dependencies
          command: |
            python -m ensurepip --upgrade  # Ensure pip is installed
            python -m pip install --upgrade pip  # Upgrade pip to the latest version
            pip install -r requirements.txt  # Install Python dependencies

      - run:
          name: Install SonarScanner
          command: |
            curl -sS https://get.sonarsource.com/sonar-scanner-cli-linux.tar.gz | tar xz -C /opt
            export PATH=$PATH:/opt/sonar-scanner-*/bin  # Add SonarScanner to PATH

      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  # Use the SONAR_TOKEN environment variable for authentication

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build