version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Using Python 3.8 docker image
    steps:
      - checkout  # Checkout the code from the repo
      
      - run:
          name: Install dependencies
          command: |
            python -m ensurepip --upgrade  # Ensure pip is installed
            python -m pip install --upgrade pip  # Upgrade pip to the latest version
            # Install dependencies, excluding pywin32 which is not required in Linux
            sed -i '/pywin32/d' requirements.txt  # Remove pywin32 from the requirements.txt for Linux environments
            pip install -r requirements.txt  # Install the remaining dependencies

      - run:
          name: Install SonarScanner
          command: |
            curl -sS https://get.sonarsource.com/sonar-scanner-cli-linux.tar.gz | tar xz -C /opt
            export PATH=$PATH:/opt/sonar-scanner-*/bin  # Add SonarScanner to PATH

      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=<your-sonarqube-project-key> \
              -Dsonar.organization=<your-sonarqube-organization> \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN  # Token from CircleCI secrets

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build